name: add_rank

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  rank:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install synapseclient challengeutils
    - name: Add rank
      run: |
        python update_ranking.py --username ${{ secrets.SYN_USERNAME }} --password ${{ secrets.SYN_PASSWORD }}